# Generated by Django 5.0.7 on 2024-07-23 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='centers',
            table='centers',
        ),
        migrations.AlterModelTable(
            name='colors',
            table='colors',
        ),
        migrations.AlterModelTable(
            name='images',
            table='images',
        ),
    ]
